name: Build and Deploy Nuxt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Nuxt image
        run: |
          docker build -t tgrow/tgrow:nuxt-${{ github.sha }} .
          docker tag tgrow/tgrow:nuxt-${{ github.sha }} tgrow/tgrow:nuxt-latest
          docker push tgrow/tgrow:nuxt-${{ github.sha }}
          docker push tgrow/tgrow:nuxt-latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted # Используем локальный runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Nuxt locally
        run: |
          cd C:\tgrow
          docker-compose pull nuxt
          docker-compose up -d nuxt
          docker system prune -f